### ISSUE TITLE
Consider CodePipeline

### ISSUE THREAD

**Issue by rarkins** [tatums/pull-request-builder#1]
Hi @tatums, I found this project from your link in the AWS discussion forum.  Like the OP there, I'm evaluating whether AWS can emulate the "typical" GitHub CI workflows like Codeship, CircleCI, Shippable, etc.

It looks like here you've managed to glue GitHub and CodeBuild together elegantly and this might satisfy the typical CI setup of sequential build/test steps. Have you considered if using CodePipeline would be worth it too?

**Comment by tatums** [comment]
Hello @rarkins - Thanks for your comment and sorry, but I didn't notice it until today. No, I haven't used CodePipeline, but I suspect that you're correct and that's the AWS preferred way to accomplish this. To be honest, I haven't used this repo for a production app. This was a weekend exploration project and I was hoping it might use it at my day job, but the fact that you can't SSH into a CodeBuild machine/container was sort of a deal breaker. 

I'm curious, have you found a good way to do this with CodePipeline?
